image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

###########
# Build Image to docker hub --------------------------------------------------------

 build_image:
   script:
     - docker build -t brunosb/image-docker-ci-tool .
     - docker push brunosb/image-docker-ci-tools:latest
