image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - tag
  - build

semantic_release:
  stage: tag
  image: node:8
  variables:
    GITLAB_TOKEN: $ACCESS_TOKEN
  before_script:
    - npm install -g semantic-release @semantic-release/gitlab-config
  script:
    - semantic-release -e @semantic-release/gitlab-config
    
  only:
    - master

build:
  stage: build
  before_script:
    - apk add --no-cache git
  script:
    - TAG=`git tag | tail -1`
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
    - docker pull $REGISTRY_IMAGE:latest || true
    - >
      docker build \
       --cache-from $REGISTRY_IMAGE:latest \
       --tag $REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA \
       --tag $REGISTRY_IMAGE:latest
       --tag $REGISTRY_IMAGE:$TAG
       .
    - docker push $REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY_IMAGE:latest
    - docker push $REGISTRY_IMAGE:$TAG
